# $Id: makefile,v 1.1 2001/05/17 20:08:29 pcharles Exp $
#
#   package net.sourceforge
#
TARGETS = \
	jpcap

# default target and tree traversal for standard targets
include ${MAKE_HOME}/chain_default.makefile
include ${MAKE_HOME}/chain_release.makefile
include ${MAKE_HOME}/chain_install.makefile
include ${MAKE_HOME}/chain_depend.makefile
include ${MAKE_HOME}/chain_clean.makefile
