# $Id: makefile,v 1.4 2003/06/24 22:34:22 pcharles Exp $
#
#   package net.sourceforge
#
TARGETS = \
	example1 \
	example2 \
	example3 \
	example4 \
	example5 \
	example6 \
	example7 \
	example15 \
	sniffer \
	misc

# default target and tree traversal for standard targets
include ${MAKE_HOME}/chain_default.makefile
include ${MAKE_HOME}/chain_release.makefile
include ${MAKE_HOME}/chain_install.makefile
include ${MAKE_HOME}/chain_depend.makefile
include ${MAKE_HOME}/chain_clean.makefile
